### ISSUE TITLE
勘误：第15章：通过注解注入属性信息

### ISSUE THREAD

**Issue by lancediarmuid** [fuzhengwei/CodeGuide#262]
UML图中最下边，“关联，写如属性”应为“关联，写入属性”
![image](https://user-images.githubusercontent.com/54305827/141086558-da405d63-5eb3-467c-83a7-1f89780f7e16.png)

**Comment by fuzhengwei** [comment]
感谢 [lancediarmuid](https://github.com/lancediarmuid)

我已将`第15章`图片`15-02`更新错字更新完毕，如下(后续随着部署会更新到站点 [bugstack.cn](https://bugstack.cn/assets/images/spring/spring-15-02.png))：

- 图片地址：[https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/spring/spring-15-02.png](https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/spring/spring-15-02.png)

![](https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/spring/spring-15-02.png)
