### ISSUE TITLE
勘误：第6章：资源加载器解析文件注册对象

### ISSUE THREAD

**Issue by ouyang1235** [fuzhengwei/CodeGuide#263]
UML图中ResourceLoader的实现类DefaultResourceLoader名称未初始化
![Snipaste_2021-11-16_11-16-16](https://user-images.githubusercontent.com/69561486/141889591-f58c3aeb-50dc-49a5-895d-2e34965ccdbb.png)

**Comment by fuzhengwei** [comment]
处理完成

![](https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/spring/spring-6-03.png?raw=true)
