### ISSUE TITLE
文件名包含win不支持的字符

### ISSUE THREAD

**Issue by 867319462** [fuzhengwei/CodeGuide#265]
2020-12-27-2020总结 | 作为技术号主的一年！.md 中的 |
`$ git clone https://github.com/fuzhengwei/CodeGuide.git
Cloning into 'CodeGuide'...
remote: Enumerating objects: 6074, done.
remote: Counting objects: 100% (2740/2740), done.
remote: Compressing objects: 100% (2181/2181), done.
remote: Total 6074 (delta 781), reused 2285 (delta 534), pack-reused 3334
Receiving objects: 100% (6074/6074), 297.36 MiB | 3.69 MiB/s, done.
Resolving deltas: 100% (1980/1980), done.
error: invalid path 'docs/md/about/me/2020-12-27-2020总结 | 作为技术号主的一年！.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by Jwnie** [comment]
文件名包含win不支持的字符 +1：
Resolving deltas: 100% (1998/1998), done.
error: invalid path 'docs/md/about/me/2020-12-27-2020总结 | 作为技术号主的一年！.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by fuzhengwei** [comment]
done！
