### ISSUE TITLE
面经手册 · 第7篇  介绍arraylist扩容时，表述有点问题。

### ISSUE THREAD

**Issue by Letusgo-Hub** [fuzhengwei/CodeGuide#266]
![image](https://user-images.githubusercontent.com/51896310/142343875-4069b684-b1d8-4d53-a724-bcbcdaeee2e2.png)
例子没有问题，描述有点不恰当，应当是扩容为 而不是扩容了。

**Comment by fuzhengwei** [comment]
赞，可以提交个PR，提交PR介绍：[https://github.com/fuzhengwei/CodeGuide/issues/260](https://github.com/fuzhengwei/CodeGuide/issues/260)

**Comment by fuzhengwei** [comment]
1. 克隆仓库
2. 在原文中点击：`“在 GitHub 上编辑此页”` -> [面经手册 · 第7篇《ArrayList也这么多知识？一个指定位置插入就把谢飞机面晕了！》](https://bugstack.cn/md/java/interview/2020-08-27-%E9%9D%A2%E7%BB%8F%E6%89%8B%E5%86%8C%20%C2%B7%20%E7%AC%AC7%E7%AF%87%E3%80%8AArrayList%E4%B9%9F%E8%BF%99%E4%B9%88%E5%A4%9A%E7%9F%A5%E8%AF%86%EF%BC%9F%E4%B8%80%E4%B8%AA%E6%8C%87%E5%AE%9A%E4%BD%8D%E7%BD%AE%E6%8F%92%E5%85%A5%E5%B0%B1%E6%8A%8A%E8%B0%A2%E9%A3%9E%E6%9C%BA%E9%9D%A2%E6%99%95%E4%BA%86%EF%BC%81%E3%80%8B.html)
