### ISSUE TITLE
五年后

### ISSUE THREAD

**Issue by yiyiyisunpei** [fuzhengwei/CodeGuide#289]
五年后，27岁的程序媛
事业：
不知道在互联网还能呆多久，不知道五年后是否还在这个行业苟活着
但是还是希望在这五年内，能尽自己最大的努力，学习更多的知识
爱情：
希望自己足够优秀的去匹配一个优秀的他，赶紧脱单吧！！！

**Comment by fuzhengwei** [comment]
可以回复到这个 issue 下：[https://github.com/fuzhengwei/CodeGuide/issues/111](https://github.com/fuzhengwei/CodeGuide/issues/111) - `祝你早日找到另一半`
