### ISSUE TITLE
mark!

### ISSUE THREAD

**Issue by Fouryearsrain** [fuzhengwei/CodeGuide#294]
1.技术上面成长了很多，自己能够独当一面！
2.经济上也希望能攒一定积蓄了，希望能付个首付！
3.身体健康！头发坚挺！

**Comment by fuzhengwei** [comment]
写到这里：[https://github.com/fuzhengwei/CodeGuide/issues/111](https://github.com/fuzhengwei/CodeGuide/issues/111)
