### ISSUE TITLE
FenrisX

### ISSUE THREAD

**Issue by 13142032717** [fuzhengwei/CodeGuide#295]
五年后也才毕业三年，但是三年属实不短了。希望到时候能找个好工作吧，在这个贩卖焦虑的时代，除了对代码的热爱，就剩下对未来的迷茫了。

**Comment by fuzhengwei** [comment]
写到这里：[https://github.com/fuzhengwei/CodeGuide/issues/111](https://github.com/fuzhengwei/CodeGuide/issues/111)
