### ISSUE TITLE
【勘误】手撸Mybatis第三章图片中的内容是否有误？

### ISSUE THREAD

**Issue by zyb284629791** [fuzhengwei/CodeGuide#305]
文档地址：docs/md/spring/develop-mybatis/2022-04-04-第3章：实现映射器的注册和使用.md
4.1的映射器标准定义实现关系图中MapperProxy#addMapper的参数是SqlSession类型，而MapperProxyFactory#newInstance中的SqlSession还是Map类型，是不是忘了从上一章的结构中修改了- -

**Comment by fuzhengwei** [comment]
是的，已修改，哈哈哈。周一更新。

**Comment by fuzhengwei** [comment]
已更新完成，需要刷新 [https://bugstack.cn/md/spring/develop-mybatis/2022-04-04-%E7%AC%AC3%E7%AB%A0%EF%BC%9A%E5%AE%9E%E7%8E%B0%E6%98%A0%E5%B0%84%E5%99%A8%E7%9A%84%E6%B3%A8%E5%86%8C%E5%92%8C%E4%BD%BF%E7%94%A8.html](https://bugstack.cn/md/spring/develop-mybatis/2022-04-04-%E7%AC%AC3%E7%AB%A0%EF%BC%9A%E5%AE%9E%E7%8E%B0%E6%98%A0%E5%B0%84%E5%99%A8%E7%9A%84%E6%B3%A8%E5%86%8C%E5%92%8C%E4%BD%BF%E7%94%A8.html)
