### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by neochief** [fuzhengwei/CodeGuide#310]
Hi!

My name is Alexander Shvets, I'm the author of both the refactoring.guru and refactoringguru.cn.

I've been notified that your website https://bugstack.cn/ and this repository contains images taken from my resource. These images are part of commercial products and are protected not only by international copyright laws but also by the Chinese MIIT (the content copyright was registered in China in 2019).

Please take down all of the images that violate my copyright to avoid further legal action.

Best regards,
Alexander Shvets
1@refactoring.guru

**Comment by fuzhengwei** [comment]
refactoringguru.cn It is a very excellent website, and I like it very much. In the process of learning design patterns, I wrote some learning notes, citing refactoring guru Cn website, this content is not for profit. The address of the application picture is marked below the picture. Do you think so, as shown in the figure.

![](https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/quote.png?raw=true)

小傅哥

**Comment by fuzhengwei** [comment]
Therefore, I would like to ask whether I can make such a reference and clearly mark the picture from your website. I also hope that more readers can come to your website to learn. Because they can jump to your website through my tagged link.

So, do you think I can continue to apply your pictures?

**Comment by neochief** [comment]
Before posting this issue, I checked several pages and found this reference only on one image. Some of the images did not include even this basic attribution.

In addition, I do allow free usage of the images (https://refactoring.guru/content-usage-policy), but only when it follows with a real hard link to the SPECIFIC page where this image is hosted on refactoringguru.cn. For example, this logistics image should be followed with a hyperlink to this page: https://refactoringguru.cn/design-patterns/factory-method, preferably with a link text "工厂方法模式 / refactoringguru.cn".

I believe in your good intentions, so I'm okay with allowing you to keep using the images, but only if these conditions are met:
- Correct attribution (that I mentioned above) is placed on all pages that use the images.
- The images are not used in any commercial product now and in the future.

**Comment by fuzhengwei** [comment]
Thank you very much. I have been waiting for your message at my computer desk. I will modify the link information according to your instructions. Thanks again. 😄

**Comment by fuzhengwei** [comment]
> Before posting this issue, I checked several pages and found this reference only on one image. Some of the images did not include even this basic attribution.
> 
> In addition, I do allow free usage of the images (https://refactoring.guru/content-usage-policy), but only when it follows with a real hard link to the SPECIFIC page where this image is hosted on refactoringguru.cn. For example, this logistics image should be followed with a hyperlink to this page: https://refactoringguru.cn/design-patterns/factory-method, preferably with a link text "工厂方法模式 / refactoringguru.cn".
> 
> I believe in your good intentions, so I'm okay with allowing you to keep using the images, but only if these conditions are met:
> 
> * Correct attribution (that I mentioned above) is placed on all pages that use the images.
> * The images are not used in any commercial product now and in the future.
---

On my blog bugstack Cn, all picture references have been corrected. You can refresh my blog for reference.

![](https://github.com/fuzhengwei/CodeGuide/blob/master/docs/.vuepress/public/assets/images/quote02.png?raw=true)

Thank you very much for your authorization. I did quote something wrong before. Thank you again.

Some others; I like your GitHub avatar very much. It looks very sunny and cheerful. I hope you can become a Chinese friend of yours. 😄

**Comment by neochief** [comment]
Thank you, I'm glad that we reached the understanding! Let's keep in touch!
