### ISSUE TITLE
《Netty+JavaFx实战：仿桌面版微信聊天》 - bugstack虫洞栈

### ISSUE THREAD

**Issue by fuzhengwei** [fuzhengwei/CodeGuide#57]
https://bugstack.cn/itstack-demo-netty-3/2020/03/04/Netty+JavaFx%E5%AE%9E%E6%88%98-%E4%BB%BF%E6%A1%8C%E9%9D%A2%E7%89%88%E5%BE%AE%E4%BF%A1%E8%81%8A%E5%A4%A9.html 

 本专栏是作者小傅哥使用JavaFx、Netty4.x、SpringBoot、Mysql等技术栈和偏向于DDD领域驱动设计方式，搭建的仿桌面版微信聊天工程实现通信核心功能。

**Comment by OnlyPiglet** [comment]
话说一楼没有福利吗 不开心

**Comment by fuzhengwei** [comment]
> @OnlyPiglet
> 话说一楼没有福利吗 不开心

哈哈哈，很久以前一楼送，后来到期了！多关注号主哇！

**Comment by mylyed** [comment]
3楼看来没戏

**Comment by mylyed** [comment]
4楼看来没戏

**Comment by mylyed** [comment]
5楼了

**Comment by fuzhengwei** [comment]
> @mylyed
> 5楼了

哈哈哈，原文内留言；https://mp.weixin.qq.com/s/THCfIT25PDZqYGETaH980A
