### ISSUE TITLE
重学 Java 设计模式：实战责任链模式「模拟618电商大促期间，项目上线流程多级负责人审批场景」 - bugstack虫洞栈

### ISSUE THREAD

**Issue by fuzhengwei** [fuzhengwei/CodeGuide#93]
https://bugstack.cn/itstack-demo-design/2020/06/18/%E9%87%8D%E5%AD%A6-Java-%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F-%E5%AE%9E%E6%88%98%E8%B4%A3%E4%BB%BB%E9%93%BE%E6%A8%A1%E5%BC%8F.html 

 射击🏹需要去靶场学习、滑雪🏂需要去雪场体验、开车🚗需要能上路实践，没有这样的技术场景给你训练，即便你有再多的想法都没法运用起来。所以，如果真的想学习一定要去一个有实操的场景，下水试试才能学会狗刨。

**Comment by HardwayLinka** [comment]
测试代码里：三级审批->无时间限制  二级审批->06-01~25  一级审批->06-11~20
代码重构后：一级审批->无时间限制  二级审批->06-11~20  三级审批->06-01~25
请问重构后这个时间是不是写错了

**Comment by fuzhengwei** [comment]
> @HardwayLinka
> 测试代码里：三级审批->无时间限制  二级审批->06-01到25  一级审批->06-11到20
> 代码重构后：一级审批->无时间限制  二级审批->06-11到20  三级审批->06-01到25
> 请问重构后这个时间是不是写错了

对，一级这在里是高级别，流程对，卡的时间节点有点不合理。👍

**Comment by aitanjiujue** [comment]
傅哥，家庭地位这一块赢了嗷
